/*
Copyright (C) 1996-1997 Id Software, Inc.
Copyright (C) 2000      Tomazquake / Nelson Fernandez
Copyright (C) 2026      Carviary SDL3 port

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// in_sdl.cpp -- SDL3 mouse, keyboard, and gamepad input

#include "quakedef.h"
#include "sdlquake.h"

// ===========================================================================
// Globals
// ===========================================================================

// Defined in gl_vid_sdl.cpp
extern SDL_Window	*sdl_window;
extern qboolean		ActiveApp, Minimized;
extern int			window_center_x, window_center_y;

// Defined in cl_main.cpp / client.h
extern cvar_t	sensitivity;
extern cvar_t	m_pitch;
extern cvar_t	m_yaw;
extern cvar_t	m_forward;
extern cvar_t	m_side;
extern cvar_t	lookstrafe;
extern cvar_t	in_mlook;

// Cvars owned by this file
cvar_t	_windowed_mouse = {"_windowed_mouse", "1", true};
cvar_t	m_filter = {"m_filter", "0", true};
cvar_t	cl_viewangles_down = {"cl_viewangles_down", "80", true};
cvar_t	cl_viewangles_up = {"cl_viewangles_up", "70", true};

// Mouse state
qboolean	mouseinitialized = false;
POINT		current_pos;
static qboolean	mouse_active = false;
static qboolean	mouse_visible = true;

static int		mouse_buttons = 0;
static int		mouse_oldbuttonstate = 0;

// Raw accumulated motion from SDL events (between frames)
static float	mx_accum = 0.0f;
static float	my_accum = 0.0f;

// Previous frame's mouse deltas (for filtering)
static float	old_mouse_x = 0.0f;
static float	old_mouse_y = 0.0f;

// Warp filtering: ignore the motion event generated by SDL_WarpMouseInWindow
static qboolean	ignore_next_motion = false;

// ===========================================================================
// Mouse show / hide / activate / deactivate
// ===========================================================================

void IN_ShowMouse (void)
{
	if (!mouse_visible)
	{
		SDL_ShowCursor();
		mouse_visible = true;
	}
}

void IN_HideMouse (void)
{
	if (mouse_visible)
	{
		SDL_HideCursor();
		mouse_visible = false;
	}
}

void IN_ActivateMouse (void)
{
	if (!mouseinitialized)
		return;
	if (mouse_active)
		return;

	mouse_active = true;

	if (sdl_window)
	{
		SDL_HideCursor();
		SDL_SetWindowRelativeMouseMode(sdl_window, true);
		// Flush any stale deltas
		float dummy_x, dummy_y;
		SDL_GetRelativeMouseState(&dummy_x, &dummy_y);
	}
}

void IN_DeactivateMouse (void)
{
	if (!mouseinitialized)
		return;
	if (!mouse_active)
		return;

	mouse_active = false;

	if (sdl_window)
	{
		SDL_SetWindowRelativeMouseMode(sdl_window, false);
		SDL_ShowCursor();
	}
}

void IN_RestoreOriginalMouseState (void)
{
	IN_DeactivateMouse();
}

void IN_SetQuakeMouseState (void)
{
	IN_ActivateMouse();
}

void IN_UpdateClipCursor (void)
{
	// No-op in SDL -- SDL handles cursor confinement via relative mouse mode.
}

// ===========================================================================
// IN_MouseEvent -- called from IN_Commands to emit key events for buttons
// ===========================================================================

void IN_MouseEvent (int mstate)
{
	int i;

	// Check each of the three mouse buttons
	for (i = 0; i < 3; i++)
	{
		int bit = (1 << i);

		if ((mstate & bit) && !(mouse_oldbuttonstate & bit))
		{
			Key_Event(K_MOUSE1 + i, true);
		}

		if (!(mstate & bit) && (mouse_oldbuttonstate & bit))
		{
			Key_Event(K_MOUSE1 + i, false);
		}
	}

	mouse_oldbuttonstate = mstate;
}

// ===========================================================================
// Scancode-to-Quake-key mapping
// ===========================================================================

static int MapSDLScancode (SDL_Scancode sc)
{
	// Letters: a-z -> 'a'-'z'
	if (sc >= SDL_SCANCODE_A && sc <= SDL_SCANCODE_Z)
		return 'a' + (sc - SDL_SCANCODE_A);

	// Number row: 1-9, 0
	if (sc >= SDL_SCANCODE_1 && sc <= SDL_SCANCODE_9)
		return '1' + (sc - SDL_SCANCODE_1);
	if (sc == SDL_SCANCODE_0)
		return '0';

	switch (sc)
	{
	case SDL_SCANCODE_ESCAPE:		return K_ESCAPE;
	case SDL_SCANCODE_RETURN:		return K_ENTER;
	case SDL_SCANCODE_KP_ENTER:		return K_ENTER;
	case SDL_SCANCODE_TAB:			return K_TAB;
	case SDL_SCANCODE_BACKSPACE:	return K_BACKSPACE;
	case SDL_SCANCODE_SPACE:		return K_SPACE;

	case SDL_SCANCODE_UP:			return K_UPARROW;
	case SDL_SCANCODE_DOWN:			return K_DOWNARROW;
	case SDL_SCANCODE_LEFT:			return K_LEFTARROW;
	case SDL_SCANCODE_RIGHT:		return K_RIGHTARROW;

	case SDL_SCANCODE_LALT:			return K_ALT;
	case SDL_SCANCODE_RALT:			return K_ALT;
	case SDL_SCANCODE_LCTRL:		return K_CTRL;
	case SDL_SCANCODE_RCTRL:		return K_CTRL;
	case SDL_SCANCODE_LSHIFT:		return K_SHIFT;
	case SDL_SCANCODE_RSHIFT:		return K_SHIFT;

	case SDL_SCANCODE_F1:			return K_F1;
	case SDL_SCANCODE_F2:			return K_F2;
	case SDL_SCANCODE_F3:			return K_F3;
	case SDL_SCANCODE_F4:			return K_F4;
	case SDL_SCANCODE_F5:			return K_F5;
	case SDL_SCANCODE_F6:			return K_F6;
	case SDL_SCANCODE_F7:			return K_F7;
	case SDL_SCANCODE_F8:			return K_F8;
	case SDL_SCANCODE_F9:			return K_F9;
	case SDL_SCANCODE_F10:			return K_F10;
	case SDL_SCANCODE_F11:			return K_F11;
	case SDL_SCANCODE_F12:			return K_F12;

	case SDL_SCANCODE_INSERT:		return K_INS;
	case SDL_SCANCODE_DELETE:		return K_DEL;
	case SDL_SCANCODE_PAGEUP:		return K_PGUP;
	case SDL_SCANCODE_PAGEDOWN:		return K_PGDN;
	case SDL_SCANCODE_HOME:			return K_HOME;
	case SDL_SCANCODE_END:			return K_END;

	case SDL_SCANCODE_PAUSE:		return K_PAUSE;

	// Grave accent / tilde -- console toggle
	case SDL_SCANCODE_GRAVE:		return '`';

	// Punctuation and symbols
	case SDL_SCANCODE_MINUS:		return '-';
	case SDL_SCANCODE_EQUALS:		return '=';
	case SDL_SCANCODE_LEFTBRACKET:	return '[';
	case SDL_SCANCODE_RIGHTBRACKET:	return ']';
	case SDL_SCANCODE_BACKSLASH:	return '\\';
	case SDL_SCANCODE_SEMICOLON:	return ';';
	case SDL_SCANCODE_APOSTROPHE:	return '\'';
	case SDL_SCANCODE_COMMA:		return ',';
	case SDL_SCANCODE_PERIOD:		return '.';
	case SDL_SCANCODE_SLASH:		return '/';

	// Numpad
	case SDL_SCANCODE_KP_0:			return '0';
	case SDL_SCANCODE_KP_1:			return '1';
	case SDL_SCANCODE_KP_2:			return '2';
	case SDL_SCANCODE_KP_3:			return '3';
	case SDL_SCANCODE_KP_4:			return '4';
	case SDL_SCANCODE_KP_5:			return '5';
	case SDL_SCANCODE_KP_6:			return '6';
	case SDL_SCANCODE_KP_7:			return '7';
	case SDL_SCANCODE_KP_8:			return '8';
	case SDL_SCANCODE_KP_9:			return '9';
	case SDL_SCANCODE_KP_PERIOD:	return '.';
	case SDL_SCANCODE_KP_DIVIDE:	return '/';
	case SDL_SCANCODE_KP_MULTIPLY:	return '*';
	case SDL_SCANCODE_KP_MINUS:		return '-';
	case SDL_SCANCODE_KP_PLUS:		return '+';

	default:
		break;
	}

	return 0; // unmapped
}

// ===========================================================================
// IN_ProcessSDLEvent -- called from Sys_SendKeyEvents for each polled event
// ===========================================================================

void IN_ProcessSDLEvent (SDL_Event *event)
{
	int key;

	switch (event->type)
	{
	// -----------------------------------------------------------------
	// Keyboard
	// -----------------------------------------------------------------
	case SDL_EVENT_KEY_DOWN:
	case SDL_EVENT_KEY_UP:
	{
		qboolean down = (event->type == SDL_EVENT_KEY_DOWN) ? true : false;
		key = MapSDLScancode(event->key.scancode);
		if (key)
			Key_Event(key, down);
		break;
	}

	// Text input for console and chat
	case SDL_EVENT_TEXT_INPUT:
	{
		const char *text = event->text.text;
		while (*text)
		{
			Key_CharEvent((unsigned char)*text);
			text++;
		}
		break;
	}

	// -----------------------------------------------------------------
	// Mouse motion -- accumulate deltas
	// -----------------------------------------------------------------
	case SDL_EVENT_MOUSE_MOTION:
		mx_accum += event->motion.xrel;
		my_accum += event->motion.yrel;
		current_pos.x = (int)event->motion.x;
		current_pos.y = (int)event->motion.y;
		{ static int mc=0; if(mc<20) {FILE*d=fopen("sdl3_angles.log","a");if(d){fprintf(d,"MOTION: xrel=%.1f yrel=%.1f x=%.1f y=%.1f accum=%.1f,%.1f\n",event->motion.xrel,event->motion.yrel,event->motion.x,event->motion.y,mx_accum,my_accum);fclose(d);}mc++;} }
		break;

	// -----------------------------------------------------------------
	// Mouse buttons
	// -----------------------------------------------------------------
	case SDL_EVENT_MOUSE_BUTTON_DOWN:
	case SDL_EVENT_MOUSE_BUTTON_UP:
	{
		qboolean down = (event->type == SDL_EVENT_MOUSE_BUTTON_DOWN) ? true : false;

		switch (event->button.button)
		{
		case SDL_BUTTON_LEFT:	Key_Event(K_MOUSE1, down); break;
		case SDL_BUTTON_RIGHT:	Key_Event(K_MOUSE2, down); break;
		case SDL_BUTTON_MIDDLE:	Key_Event(K_MOUSE3, down); break;
		default: break;
		}

		// Update button state bitmask for IN_MouseEvent / IN_Commands
		if (down)
		{
			if (event->button.button == SDL_BUTTON_LEFT)	mouse_buttons |= 1;
			if (event->button.button == SDL_BUTTON_RIGHT)	mouse_buttons |= 2;
			if (event->button.button == SDL_BUTTON_MIDDLE)	mouse_buttons |= 4;
		}
		else
		{
			if (event->button.button == SDL_BUTTON_LEFT)	mouse_buttons &= ~1;
			if (event->button.button == SDL_BUTTON_RIGHT)	mouse_buttons &= ~2;
			if (event->button.button == SDL_BUTTON_MIDDLE)	mouse_buttons &= ~4;
		}
		break;
	}

	// -----------------------------------------------------------------
	// Mouse wheel
	// -----------------------------------------------------------------
	case SDL_EVENT_MOUSE_WHEEL:
		if (event->wheel.y > 0)
		{
			Key_Event(K_MWHEELUP, true);
			Key_Event(K_MWHEELUP, false);
		}
		else if (event->wheel.y < 0)
		{
			Key_Event(K_MWHEELDOWN, true);
			Key_Event(K_MWHEELDOWN, false);
		}
		break;

	// -----------------------------------------------------------------
	// Window focus
	// -----------------------------------------------------------------
	case SDL_EVENT_WINDOW_FOCUS_GAINED:
		ActiveApp = true;
		break;

	case SDL_EVENT_WINDOW_FOCUS_LOST:
		ActiveApp = false;

		// Release mouse when we lose focus
		IN_DeactivateMouse();
		break;

	case SDL_EVENT_WINDOW_MINIMIZED:
		Minimized = true;
		break;

	case SDL_EVENT_WINDOW_RESTORED:
		Minimized = false;
		break;

	// -----------------------------------------------------------------
	// Quit
	// -----------------------------------------------------------------
	case SDL_EVENT_QUIT:
		Sys_Quit();
		break;

	default:
		break;
	}
}

// ===========================================================================
// IN_Init / IN_Shutdown
// ===========================================================================

void IN_Init (void)
{
	Cvar_RegisterVariable(&_windowed_mouse);
	Cvar_RegisterVariable(&m_filter);
	Cvar_RegisterVariable(&cl_viewangles_down);
	Cvar_RegisterVariable(&cl_viewangles_up);

	// Enable text input for console typing
	if (sdl_window)
		SDL_StartTextInput(sdl_window);

	mouseinitialized = true;

	// Activate mouse capture for gameplay
	IN_ActivateMouse();

	Con_Printf("SDL mouse input initialized\n");
}

void IN_Shutdown (void)
{
	IN_DeactivateMouse();
	mouseinitialized = false;
}

// ===========================================================================
// IN_Commands -- let devices push commands into the script buffer
// ===========================================================================

void IN_Commands (void)
{
	// Always keep mouse captured when the app is active and we're in game
	if (ActiveApp && key_dest == key_game)
	{
		if (!mouse_active)
			IN_ActivateMouse();
	}
	else
	{
		if (mouse_active)
			IN_DeactivateMouse();
	}
}

// ===========================================================================
// IN_Accumulate -- called from the main loop to gather mouse input
// ===========================================================================

void IN_Accumulate (void)
{
	// Mouse motion is already accumulated in mx_accum / my_accum
	// by IN_ProcessSDLEvent. Nothing extra to do here.
}

// ===========================================================================
// IN_Move -- apply accumulated mouse / gamepad motion to the usercmd
// ===========================================================================

void IN_Move (usercmd_t *cmd)
{
	float	mx, my;

	if (!mouse_active || key_dest != key_game)
		return;

	// Read accumulated mouse deltas directly from SDL (no events, no warps)
	float raw_mx, raw_my;
	SDL_GetRelativeMouseState(&raw_mx, &raw_my);
	mx = raw_mx;
	my = raw_my;

	// Mouse filtering: average this frame's delta with the previous frame's
	if (m_filter.value)
	{
		mx = (mx + old_mouse_x) * 0.5f;
		my = (my + old_mouse_y) * 0.5f;
	}

	old_mouse_x = mx;
	old_mouse_y = my;

	// Apply sensitivity
	mx *= sensitivity.value;
	my *= sensitivity.value;

	// If strafing with mouse, add to sidemove
	if ((in_strafe.state & 1) || (lookstrafe.value && (in_mlook.value)))
	{
		cmd->sidemove += m_side.value * mx;
	}
	else
	{
		cl.viewangles[YAW] -= m_yaw.value * mx;
	}

	if (in_mlook.value)
		V_StopPitchDrift();

	if ((in_mlook.value) && !(in_strafe.state & 1))
	{
		cl.viewangles[PITCH] += m_pitch.value * my;

		// Clamp pitch
		if (cl.viewangles[PITCH] > 80.0f)
			cl.viewangles[PITCH] = 80.0f;
		if (cl.viewangles[PITCH] < -70.0f)
			cl.viewangles[PITCH] = -70.0f;
	}
	else
	{
		cmd->forwardmove -= m_forward.value * my;
	}
}

// ===========================================================================
// IN_ClearStates -- reset all input state
// ===========================================================================

void IN_ClearStates (void)
{
	mx_accum = 0.0f;
	my_accum = 0.0f;
	old_mouse_x = 0.0f;
	old_mouse_y = 0.0f;
	mouse_oldbuttonstate = 0;
	mouse_buttons = 0;
}
